### ISSUE TITLE
Setup documentation

### ISSUE THREAD

**Issue by zketosis** [zketosis/ESP32-SmartCore#3]
Would like to know what setup you use for your esp32 development. 
List PC/mac software (where to download) and libraries you use.

Then all development can be the same.

**Comment by Arroak** [comment]
1. Development Machine : PC running Ubuntu 22.04.2 LTS  OS (https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668?_ga=2.157601907.871555001.1691147356-634783622.1691147356)
2.Development Environment : Microsoft Visual Studio Code (VSCode)  (https://code.visualstudio.com/download)
3. VSCode Extension for Development : PlatformIO  (https://platformio.org/install/ide?install=vscode) for installation steps 
4. Development Environment version : PlatformIO IDE 3.3.1  (PlatformIO core version 1.2.1)
5. PlatformIO Developement Framework : Arduino 
6. ESP32 Microcontroller Version : M5Stack Core ESP32
7.  Libraries : Arduino.h

**Comment by Arroak** [comment]
The list will be updated as the project continues
